services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app:cached # Mount โค้ดจาก Host ไปยัง Container
      - /app/node_modules # ป้องกันการเขียนทับ node_modules
      - /app/.next # เก็บไฟล์ Build เพื่อลดเวลาบิลด์
    command: npm run start
    networks:
      - app-network
      - smog_nginx_network

networks:
  app-network:
    driver: bridge
  smog_nginx_network:
    external: true
