services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
      - smog_nginx_network

networks:
  app-network:
    driver: bridge
  smog_nginx_network:
    external: true
