name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code จาก GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # เชื่อมต่อและ Deploy ไปยังเซิร์ฟเวอร์
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          port: ${{ secrets.PROD_SERVER_PORT }}

          # คำสั่งบนเซิร์ฟเวอร์
          script: |
            cd ~/CICD/smog-epinorth
            git fetch origin main
            git diff --exit-code HEAD origin/main || (
              echo "New changes detected. Pulling latest code..."
              git reset --hard origin/main
              git pull origin main
              npm ci --production
              pm2 restart app || pm2 start npm --name "app" -- run start
            )
            echo "Deployment finished."
