name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.2.0"

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm test

      # - name: Build Next.js app
      #   run: npm run build

      # - name: Build Docker image
      #   run: docker build -t kamolsomkrai/smog-epinorth:${{ github.sha }} .

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push Docker image
      #   run: docker push kamolsomkrai/smog-epinorth:${{ github.sha }}

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /CICD/epinorth
            docker pull kamolsomkrai/smog-epinorth:${{ github.sha }}
            docker-compose down
            docker-compose up -d
